#!/usr/bin/env -S deno run --allow-read
// Emit a C translation unit of _Static_asserts from the host ABI schema.
//
// Standalone Deno script, no third-party dependencies. Given the path to
// packages/linux-guest/src/abi.ts as its single argument, it dynamic-imports
// the schema and prints one _Static_assert per ABI fact to stdout. The
// guest-agent build compiles the result with `$CC -c` (it is never run):
// every assert mirrors a value the host library depends on, so any drift
// between the vendored kernel headers and abi.ts becomes a build failure.

interface ScalarCheck {
  c: string;
  value: number;
}
interface FieldCheck {
  c: string;
  offset: number;
  size: number | null;
}
interface StructCheck {
  c: string;
  sizeof: number | null;
  fields: FieldCheck[];
}
interface ExprCheck {
  name: string;
  expr: string;
}
interface AbiChecks {
  includes: string[];
  scalars: ScalarCheck[];
  structs: StructCheck[];
  exprs: ExprCheck[];
}

function fail(message: string): never {
  console.error(`gen-abi-check: ${message}`);
  Deno.exit(1);
}

function cString(text: string): string {
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function assert(condition: string, message: string): string {
  return `_Static_assert(${condition}, ${cString(message)});`;
}

async function main() {
  const arg = Deno.args[0];
  if (!arg || Deno.args.length !== 1) {
    fail("usage: gen-abi-check.ts <path-to-abi.ts>");
  }

  const url = new URL(arg, `file://${Deno.cwd()}/`).href;
  const module = await import(url);
  const checks = module.abiChecks as AbiChecks | undefined;
  if (!checks || !Array.isArray(checks.scalars) || !Array.isArray(checks.includes)) {
    fail(`${arg} does not export a valid \`abiChecks\``);
  }

  const lines: string[] = [];
  lines.push("/* Generated by packages/guest-agent/gen-abi-check.ts. Do not edit. */");
  lines.push("/* Compiled (never run) to verify abi.ts against the guest kernel headers. */");
  lines.push("");
  for (const include of checks.includes) lines.push(include);
  lines.push("");

  lines.push("/* Scalar constants. */");
  for (const scalar of checks.scalars) {
    lines.push(
      assert(`(long)(${scalar.c}) == ${scalar.value}L`, `abi: ${scalar.c} == ${scalar.value}`),
    );
  }
  lines.push("");

  lines.push("/* Struct layouts. */");
  for (const struct of checks.structs) {
    for (const field of struct.fields) {
      lines.push(
        assert(
          `offsetof(${struct.c}, ${field.c}) == ${field.offset}`,
          `abi: offsetof(${struct.c}, ${field.c}) == ${field.offset}`,
        ),
      );
      if (field.size !== null) {
        lines.push(
          assert(
            `sizeof(((${struct.c} *)0)->${field.c}) == ${field.size}`,
            `abi: sizeof(${struct.c}.${field.c}) == ${field.size}`,
          ),
        );
      }
    }
    if (struct.sizeof !== null) {
      lines.push(
        assert(
          `sizeof(${struct.c}) == ${struct.sizeof}`,
          `abi: sizeof(${struct.c}) == ${struct.sizeof}`,
        ),
      );
    }
    lines.push("");
  }

  lines.push("/* Wait-status macro semantics. */");
  for (const expr of checks.exprs) {
    lines.push(assert(expr.expr, `abi: ${expr.name}`));
  }
  lines.push("");

  console.log(lines.join("\n"));
}

await main();
