{
  pkgs,
  stdenv,
  src ? pkgs.fetchzip {
    url = "https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz";
    hash = "sha256-VnE/TPw/fOD9I3aVmMfzZKdULcmEoljpAPjugMiq+p4=";
  },
  busybox,
  vm-test,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "findutils";
  version = "4.10.0";
  inherit src;

  configureFlags = [
    "--disable-nls"
    # Compile guest-visible paths into locate and updatedb, then stage the
    # installation under $out. Keep find/xargs in /bin so they shadow the
    # BusyBox applets in the distro's normal PATH.
    "--prefix=/"
    "--libexecdir=/usr/libexec"
    "--localstatedir=/var"
  ];

  # updatedb is generated by the Makefile and otherwise captures configure's
  # build-host sort. The guest base layer provides /usr/bin/sort and /bin/sh, so
  # retaining updatedb/locate is useful without adding either to this slice.
  makeFlags = [ "SORT=/usr/bin/sort" ];
  installFlags = [ "DESTDIR=$(out)" ];
  dontPatchShebangs = true;

  # find's -exec/-execdir/-ok create the child with fork()+execvp(). wasm has no
  # fork(); rewrite launch() to posix_spawnp (clone+execve), carrying the
  # between-fork-and-exec work -- the /dev/null stdin redirect and the chdir into
  # wd_for_exec that prep_child_for_exec() did -- as posix_spawn file actions.
  # xargs already routes through gnulib's spawn (posix_spawnp), so it needs no
  # patch.
  patches = [ ./wasm-posix-spawn.patch ];

  postInstall = ''
    ! grep -F /nix/store $out/bin/updatedb
    ! grep -F "$out" $out/bin/locate
  '';

  passthru.checks = {
    functionality = vm-test.vmTest {
      name = "findutils-functionality";
      initramfs = vm-test.mkInitramfs {
        name = "findutils-functionality";
        init = ./functionality-test.sh;
        # busybox first, findutils last: the GNU binary must shadow busybox's applet.
        contents = [
          busybox
          finalAttrs.finalPackage
        ];
      };
    };
  };
})
